/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using LoanStreet.LoanServicing.Api;
using Xunit;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///     Class for testing DealsControllerApi
    /// </summary>
    /// <remarks>
    ///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    ///     Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DealsControllerApiTests : IDisposable
    {
        public DealsControllerApiTests()
        {
            instance = new DealsControllerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        private DealsControllerApi instance;


        /// <summary>
        ///     Test CreateDeal
        /// </summary>
        [Fact]
        public void CreateDealTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Deal deal = null;
            //var response = instance.CreateDeal(deal);
            //Assert.IsType<Deal> (response, "response is Deal");
        }

        /// <summary>
        ///     Test FetchDeals
        /// </summary>
        [Fact]
        public void FetchDealsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.FetchDeals();
            //Assert.IsType<List<Deal>> (response, "response is List<Deal>");
        }

        /// <summary>
        ///     Test FetchDeal
        /// </summary>
        [Fact]
        public void FetchDealTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string dealId = null;
            //var response = instance.FetchDeal(dealId);
            //Assert.IsType<Deal> (response, "response is Deal");
        }

        /// <summary>
        ///     Test an instance of DealsControllerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DealsControllerApi
            //Assert.IsType(typeof(DealsControllerApi), instance, "instance is a DealsControllerApi");
        }

        /// <summary>
        ///     Test UpdateDeal
        /// </summary>
        [Fact]
        public void UpdateDealTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string dealId = null;
            //Deal deal = null;
            //var response = instance.UpdateDeal(dealId, deal);
            //Assert.IsType<Deal> (response, "response is Deal");
        }
    }
}