/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using LoanStreet.LoanServicing.Client;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing FinanceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FinanceApiTests : IDisposable
    {
        private FinanceApi instance;

        public FinanceApiTests()
        {
            instance = new FinanceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FinanceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FinanceApi
            //Assert.IsType(typeof(FinanceApi), instance, "instance is a FinanceApi");
        }

        
        /// <summary>
        /// Test NextBusinessDayResponse
        /// </summary>
        [Fact]
        public void NextBusinessDayResponseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime inputDate = null;
            //var response = instance.NextBusinessDayResponse(inputDate);
            //Assert.IsType<BusinessDayResponse> (response, "response is BusinessDayResponse");
        }
        
        /// <summary>
        /// Test PreviousBusinessDayResponse
        /// </summary>
        [Fact]
        public void PreviousBusinessDayResponseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime inputDate = null;
            //var response = instance.PreviousBusinessDayResponse(inputDate);
            //Assert.IsType<BusinessDayResponse> (response, "response is BusinessDayResponse");
        }
        
    }

}
