/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using LoanStreet.LoanServicing.Client;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing LoansApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LoansApiTests : IDisposable
    {
        private LoansApi instance;

        public LoansApiTests()
        {
            instance = new LoansApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoansApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LoansApi
            //Assert.IsType(typeof(LoansApi), instance, "instance is a LoansApi");
        }

        
        /// <summary>
        /// Test CreateLoan
        /// </summary>
        [Fact]
        public void CreateLoanTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Loan loan = null;
            //var response = instance.CreateLoan(loan);
            //Assert.IsType<Loan> (response, "response is Loan");
        }
        
        /// <summary>
        /// Test GetLoan
        /// </summary>
        [Fact]
        public void GetLoanTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string loanId = null;
            //var response = instance.GetLoan(loanId);
            //Assert.IsType<Loan> (response, "response is Loan");
        }
        
        /// <summary>
        /// Test ListLoans
        /// </summary>
        [Fact]
        public void ListLoansTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListLoans();
            //Assert.IsType<List<Loan>> (response, "response is List<Loan>");
        }
        
    }

}
