/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using LoanStreet.LoanServicing.Client;
using LoanStreet.LoanServicing.Model;

namespace LoanStreet.LoanServicing.Api
{
    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoanInvoicesControllerApiSync : IApiAccessor
    {
        #region Synchronous Operations

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoice"> (optional)</param>
        /// <returns>Invoice</returns>
        Invoice CreateInvoice(string loanId, Invoice invoice = default);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoice"> (optional)</param>
        /// <returns>ApiResponse of Invoice</returns>
        ApiResponse<Invoice> CreateInvoiceWithHttpInfo(string loanId, Invoice invoice = default);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoiceId"></param>
        /// <returns>Invoice</returns>
        Invoice GetInvoice(string loanId, string invoiceId);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoiceId"></param>
        /// <returns>ApiResponse of Invoice</returns>
        ApiResponse<Invoice> GetInvoiceWithHttpInfo(string loanId, string invoiceId);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <returns>List&lt;Invoice&gt;</returns>
        List<Invoice> ListInvoiceHistory(string loanId);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <returns>ApiResponse of List&lt;Invoice&gt;</returns>
        ApiResponse<List<Invoice>> ListInvoiceHistoryWithHttpInfo(string loanId);

        #endregion Synchronous Operations
    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoanInvoicesControllerApiAsync : IApiAccessor
    {
        #region Asynchronous Operations

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoice"> (optional)</param>
        /// <returns>Task of Invoice</returns>
        Task<Invoice> CreateInvoiceAsync(string loanId, Invoice invoice = default);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoice"> (optional)</param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        Task<ApiResponse<Invoice>> CreateInvoiceAsyncWithHttpInfo(string loanId, Invoice invoice = default);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoiceId"></param>
        /// <returns>Task of Invoice</returns>
        Task<Invoice> GetInvoiceAsync(string loanId, string invoiceId);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoiceId"></param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        Task<ApiResponse<Invoice>> GetInvoiceAsyncWithHttpInfo(string loanId, string invoiceId);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <returns>Task of List&lt;Invoice&gt;</returns>
        Task<List<Invoice>> ListInvoiceHistoryAsync(string loanId);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <returns>Task of ApiResponse (List&lt;Invoice&gt;)</returns>
        Task<ApiResponse<List<Invoice>>> ListInvoiceHistoryAsyncWithHttpInfo(string loanId);

        #endregion Asynchronous Operations
    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoanInvoicesControllerApi : ILoanInvoicesControllerApiSync, ILoanInvoicesControllerApiAsync
    {
    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class LoanInvoicesControllerApi : ILoanInvoicesControllerApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        ///     Initializes a new instance of the <see cref="LoanInvoicesControllerApi" /> class.
        /// </summary>
        /// <returns></returns>
        public LoanInvoicesControllerApi() : this((string) null)
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="LoanInvoicesControllerApi" /> class.
        /// </summary>
        /// <returns></returns>
        public LoanInvoicesControllerApi(string basePath)
        {
            Configuration = LoanServicing.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                new Configuration {BasePath = basePath}
            );
            Client = new ApiClient(Configuration.BasePath);
            AsynchronousClient = new ApiClient(Configuration.BasePath);
            ExceptionFactory = LoanServicing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="LoanInvoicesControllerApi" /> class
        ///     using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LoanInvoicesControllerApi(Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            Configuration = LoanServicing.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                configuration
            );
            Client = new ApiClient(Configuration.BasePath);
            AsynchronousClient = new ApiClient(Configuration.BasePath);
            ExceptionFactory = LoanServicing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="LoanInvoicesControllerApi" /> class
        ///     using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public LoanInvoicesControllerApi(ISynchronousClient client, IAsynchronousClient asyncClient,
            IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            Client = client;
            AsynchronousClient = asyncClient;
            Configuration = configuration;
            ExceptionFactory = LoanServicing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     The client for accessing this underlying API asynchronously.
        /// </summary>
        public IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        ///     The client for accessing this underlying API synchronously.
        /// </summary>
        public ISynchronousClient Client { get; set; }

        /// <summary>
        ///     Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return Configuration.BasePath;
        }

        /// <summary>
        ///     Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IReadableConfiguration Configuration { get; set; }

        /// <summary>
        ///     Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                return _exceptionFactory;
            }
            set => _exceptionFactory = value;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoice"> (optional)</param>
        /// <returns>Invoice</returns>
        public Invoice CreateInvoice(string loanId, Invoice invoice = default)
        {
            var localVarResponse = CreateInvoiceWithHttpInfo(loanId, invoice);
            return localVarResponse.Data;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoice"> (optional)</param>
        /// <returns>ApiResponse of Invoice</returns>
        public ApiResponse<Invoice> CreateInvoiceWithHttpInfo(string loanId, Invoice invoice = default)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400,
                    "Missing required parameter 'loanId' when calling LoanInvoicesControllerApi->CreateInvoice");

            var localVarRequestOptions = new RequestOptions();

            string[] _contentTypes =
            {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts =
            {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId",
                    ClientUtils.ParameterToString(loanId)); // path parameter
            localVarRequestOptions.Data = invoice;


            // make the HTTP request
            var localVarResponse = Client.Post<Invoice>("/v1/private/loans/{loanId}/invoices", localVarRequestOptions,
                Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("CreateInvoice", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoice"> (optional)</param>
        /// <returns>Task of Invoice</returns>
        public async Task<Invoice> CreateInvoiceAsync(string loanId, Invoice invoice = default)
        {
            var localVarResponse = await CreateInvoiceAsyncWithHttpInfo(loanId, invoice);
            return localVarResponse.Data;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoice"> (optional)</param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        public async Task<ApiResponse<Invoice>> CreateInvoiceAsyncWithHttpInfo(string loanId, Invoice invoice = default)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400,
                    "Missing required parameter 'loanId' when calling LoanInvoicesControllerApi->CreateInvoice");


            var localVarRequestOptions = new RequestOptions();

            string[] _contentTypes =
            {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts =
            {
                "application/json"
            };

            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);

            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);

            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId",
                    ClientUtils.ParameterToString(loanId)); // path parameter
            localVarRequestOptions.Data = invoice;


            // make the HTTP request

            var localVarResponse = await AsynchronousClient.PostAsync<Invoice>("/v1/private/loans/{loanId}/invoices",
                localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("CreateInvoice", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoiceId"></param>
        /// <returns>Invoice</returns>
        public Invoice GetInvoice(string loanId, string invoiceId)
        {
            var localVarResponse = GetInvoiceWithHttpInfo(loanId, invoiceId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoiceId"></param>
        /// <returns>ApiResponse of Invoice</returns>
        public ApiResponse<Invoice> GetInvoiceWithHttpInfo(string loanId, string invoiceId)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400,
                    "Missing required parameter 'loanId' when calling LoanInvoicesControllerApi->GetInvoice");

            // verify the required parameter 'invoiceId' is set
            if (invoiceId == null)
                throw new ApiException(400,
                    "Missing required parameter 'invoiceId' when calling LoanInvoicesControllerApi->GetInvoice");

            var localVarRequestOptions = new RequestOptions();

            string[] _contentTypes =
            {
            };

            // to determine the Accept header
            string[] _accepts =
            {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId",
                    ClientUtils.ParameterToString(loanId)); // path parameter
            if (invoiceId != null)
                localVarRequestOptions.PathParameters.Add("invoiceId",
                    ClientUtils.ParameterToString(invoiceId)); // path parameter


            // make the HTTP request
            var localVarResponse = Client.Get<Invoice>("/v1/private/loans/{loanId}/invoices/{invoiceId}",
                localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("GetInvoice", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoiceId"></param>
        /// <returns>Task of Invoice</returns>
        public async Task<Invoice> GetInvoiceAsync(string loanId, string invoiceId)
        {
            var localVarResponse = await GetInvoiceAsyncWithHttpInfo(loanId, invoiceId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="invoiceId"></param>
        /// <returns>Task of ApiResponse (Invoice)</returns>
        public async Task<ApiResponse<Invoice>> GetInvoiceAsyncWithHttpInfo(string loanId, string invoiceId)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400,
                    "Missing required parameter 'loanId' when calling LoanInvoicesControllerApi->GetInvoice");

            // verify the required parameter 'invoiceId' is set
            if (invoiceId == null)
                throw new ApiException(400,
                    "Missing required parameter 'invoiceId' when calling LoanInvoicesControllerApi->GetInvoice");


            var localVarRequestOptions = new RequestOptions();

            string[] _contentTypes =
            {
            };

            // to determine the Accept header
            string[] _accepts =
            {
                "application/json"
            };

            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);

            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);

            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId",
                    ClientUtils.ParameterToString(loanId)); // path parameter
            if (invoiceId != null)
                localVarRequestOptions.PathParameters.Add("invoiceId",
                    ClientUtils.ParameterToString(invoiceId)); // path parameter


            // make the HTTP request

            var localVarResponse = await AsynchronousClient.GetAsync<Invoice>(
                "/v1/private/loans/{loanId}/invoices/{invoiceId}", localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("GetInvoice", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <returns>List&lt;Invoice&gt;</returns>
        public List<Invoice> ListInvoiceHistory(string loanId)
        {
            var localVarResponse = ListInvoiceHistoryWithHttpInfo(loanId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <returns>ApiResponse of List&lt;Invoice&gt;</returns>
        public ApiResponse<List<Invoice>> ListInvoiceHistoryWithHttpInfo(string loanId)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400,
                    "Missing required parameter 'loanId' when calling LoanInvoicesControllerApi->ListInvoiceHistory");

            var localVarRequestOptions = new RequestOptions();

            string[] _contentTypes =
            {
            };

            // to determine the Accept header
            string[] _accepts =
            {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId",
                    ClientUtils.ParameterToString(loanId)); // path parameter


            // make the HTTP request
            var localVarResponse = Client.Get<List<Invoice>>("/v1/private/loans/{loanId}/invoices",
                localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("ListInvoiceHistory", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <returns>Task of List&lt;Invoice&gt;</returns>
        public async Task<List<Invoice>> ListInvoiceHistoryAsync(string loanId)
        {
            var localVarResponse = await ListInvoiceHistoryAsyncWithHttpInfo(loanId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <returns>Task of ApiResponse (List&lt;Invoice&gt;)</returns>
        public async Task<ApiResponse<List<Invoice>>> ListInvoiceHistoryAsyncWithHttpInfo(string loanId)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400,
                    "Missing required parameter 'loanId' when calling LoanInvoicesControllerApi->ListInvoiceHistory");


            var localVarRequestOptions = new RequestOptions();

            string[] _contentTypes =
            {
            };

            // to determine the Accept header
            string[] _accepts =
            {
                "application/json"
            };

            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);

            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);

            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId",
                    ClientUtils.ParameterToString(loanId)); // path parameter


            // make the HTTP request

            var localVarResponse =
                await AsynchronousClient.GetAsync<List<Invoice>>("/v1/private/loans/{loanId}/invoices",
                    localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("ListInvoiceHistory", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }
    }
}