/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Threading.Tasks;
using LoanStreet.LoanServicing.Client;
using LoanStreet.LoanServicing.Model;

namespace LoanStreet.LoanServicing.Api
{
    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoanSyndicationsControllerApiSync : IApiAccessor
    {
        #region Synchronous Operations

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="sale"> (optional)</param>
        /// <returns>Sale</returns>
        Sale CreateSyndication(string loanId, Sale sale = default);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="sale"> (optional)</param>
        /// <returns>ApiResponse of Sale</returns>
        ApiResponse<Sale> CreateSyndicationWithHttpInfo(string loanId, Sale sale = default);

        #endregion Synchronous Operations
    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoanSyndicationsControllerApiAsync : IApiAccessor
    {
        #region Asynchronous Operations

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="sale"> (optional)</param>
        /// <returns>Task of Sale</returns>
        Task<Sale> CreateSyndicationAsync(string loanId, Sale sale = default);

        /// <summary>
        /// </summary>
        /// <remarks>
        /// </remarks>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="sale"> (optional)</param>
        /// <returns>Task of ApiResponse (Sale)</returns>
        Task<ApiResponse<Sale>> CreateSyndicationAsyncWithHttpInfo(string loanId, Sale sale = default);

        #endregion Asynchronous Operations
    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoanSyndicationsControllerApi : ILoanSyndicationsControllerApiSync,
        ILoanSyndicationsControllerApiAsync
    {
    }

    /// <summary>
    ///     Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class LoanSyndicationsControllerApi : ILoanSyndicationsControllerApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        ///     Initializes a new instance of the <see cref="LoanSyndicationsControllerApi" /> class.
        /// </summary>
        /// <returns></returns>
        public LoanSyndicationsControllerApi() : this((string) null)
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="LoanSyndicationsControllerApi" /> class.
        /// </summary>
        /// <returns></returns>
        public LoanSyndicationsControllerApi(string basePath)
        {
            Configuration = LoanServicing.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                new Configuration {BasePath = basePath}
            );
            Client = new ApiClient(Configuration.BasePath);
            AsynchronousClient = new ApiClient(Configuration.BasePath);
            ExceptionFactory = LoanServicing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="LoanSyndicationsControllerApi" /> class
        ///     using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LoanSyndicationsControllerApi(Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            Configuration = LoanServicing.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                configuration
            );
            Client = new ApiClient(Configuration.BasePath);
            AsynchronousClient = new ApiClient(Configuration.BasePath);
            ExceptionFactory = LoanServicing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="LoanSyndicationsControllerApi" /> class
        ///     using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public LoanSyndicationsControllerApi(ISynchronousClient client, IAsynchronousClient asyncClient,
            IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            Client = client;
            AsynchronousClient = asyncClient;
            Configuration = configuration;
            ExceptionFactory = LoanServicing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        ///     The client for accessing this underlying API asynchronously.
        /// </summary>
        public IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        ///     The client for accessing this underlying API synchronously.
        /// </summary>
        public ISynchronousClient Client { get; set; }

        /// <summary>
        ///     Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return Configuration.BasePath;
        }

        /// <summary>
        ///     Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IReadableConfiguration Configuration { get; set; }

        /// <summary>
        ///     Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                return _exceptionFactory;
            }
            set => _exceptionFactory = value;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="sale"> (optional)</param>
        /// <returns>Sale</returns>
        public Sale CreateSyndication(string loanId, Sale sale = default)
        {
            var localVarResponse = CreateSyndicationWithHttpInfo(loanId, sale);
            return localVarResponse.Data;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="sale"> (optional)</param>
        /// <returns>ApiResponse of Sale</returns>
        public ApiResponse<Sale> CreateSyndicationWithHttpInfo(string loanId, Sale sale = default)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400,
                    "Missing required parameter 'loanId' when calling LoanSyndicationsControllerApi->CreateSyndication");

            var localVarRequestOptions = new RequestOptions();

            string[] _contentTypes =
            {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts =
            {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId",
                    ClientUtils.ParameterToString(loanId)); // path parameter
            localVarRequestOptions.Data = sale;


            // make the HTTP request
            var localVarResponse = Client.Post<Sale>("/v1/private/loans/{loanId}/syndications", localVarRequestOptions,
                Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("CreateSyndication", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="sale"> (optional)</param>
        /// <returns>Task of Sale</returns>
        public async Task<Sale> CreateSyndicationAsync(string loanId, Sale sale = default)
        {
            var localVarResponse = await CreateSyndicationAsyncWithHttpInfo(loanId, sale);
            return localVarResponse.Data;
        }

        /// <summary>
        /// </summary>
        /// <exception cref="LoanStreet.LoanServicing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId"></param>
        /// <param name="sale"> (optional)</param>
        /// <returns>Task of ApiResponse (Sale)</returns>
        public async Task<ApiResponse<Sale>> CreateSyndicationAsyncWithHttpInfo(string loanId, Sale sale = default)
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new ApiException(400,
                    "Missing required parameter 'loanId' when calling LoanSyndicationsControllerApi->CreateSyndication");


            var localVarRequestOptions = new RequestOptions();

            string[] _contentTypes =
            {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts =
            {
                "application/json"
            };

            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);

            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);

            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId",
                    ClientUtils.ParameterToString(loanId)); // path parameter
            localVarRequestOptions.Data = sale;


            // make the HTTP request

            var localVarResponse = await AsynchronousClient.PostAsync<Sale>("/v1/private/loans/{loanId}/syndications",
                localVarRequestOptions, Configuration);

            if (ExceptionFactory != null)
            {
                var _exception = ExceptionFactory("CreateSyndication", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }
    }
}