/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///     Class for testing Deal
    /// </summary>
    /// <remarks>
    ///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    ///     Please update the test case below to test the model.
    /// </remarks>
    public class DealTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Deal
        //private Deal instance;

        public void Dispose()
        {
            // Cleanup when everything is done.
        }


        /// <summary>
        ///     Test the property 'DealId'
        /// </summary>
        [Fact]
        public void DealIdTest()
        {
            // TODO unit test for the property 'DealId'
        }

        /// <summary>
        ///     Test an instance of Deal
        /// </summary>
        [Fact]
        public void DealInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Deal
            //Assert.IsInstanceOfType<Deal> (instance, "variable 'instance' is a Deal");
        }

        /// <summary>
        ///     Test the property 'Facility'
        /// </summary>
        [Fact]
        public void FacilityTest()
        {
            // TODO unit test for the property 'Facility'
        }

        /// <summary>
        ///     Test the property 'Tranches'
        /// </summary>
        [Fact]
        public void TranchesTest()
        {
            // TODO unit test for the property 'Tranches'
        }
    }
}