/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing Facility
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FacilityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Facility
        //private Facility instance;

        public FacilityTests()
        {
            // TODO uncomment below to create an instance of Facility
            //instance = new Facility();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Facility
        /// </summary>
        [Fact]
        public void FacilityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Facility
            //Assert.IsInstanceOfType<Facility> (instance, "variable 'instance' is a Facility");
        }


        /// <summary>
        /// Test the property 'FacilityId'
        /// </summary>
        [Fact]
        public void FacilityIdTest()
        {
            // TODO unit test for the property 'FacilityId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TimeZoneId'
        /// </summary>
        [Fact]
        public void TimeZoneIdTest()
        {
            // TODO unit test for the property 'TimeZoneId'
        }
        /// <summary>
        /// Test the property 'Institutions'
        /// </summary>
        [Fact]
        public void InstitutionsTest()
        {
            // TODO unit test for the property 'Institutions'
        }
        /// <summary>
        /// Test the property 'Tranches'
        /// </summary>
        [Fact]
        public void TranchesTest()
        {
            // TODO unit test for the property 'Tranches'
        }
        /// <summary>
        /// Test the property 'Borrowings'
        /// </summary>
        [Fact]
        public void BorrowingsTest()
        {
            // TODO unit test for the property 'Borrowings'
        }

    }

}
