/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing FacilityInstitutionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FacilityInstitutionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FacilityInstitutionDto
        //private FacilityInstitutionDto instance;

        public FacilityInstitutionDtoTests()
        {
            // TODO uncomment below to create an instance of FacilityInstitutionDto
            //instance = new FacilityInstitutionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FacilityInstitutionDto
        /// </summary>
        [Fact]
        public void FacilityInstitutionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FacilityInstitutionDto
            //Assert.IsInstanceOfType<FacilityInstitutionDto> (instance, "variable 'instance' is a FacilityInstitutionDto");
        }


        /// <summary>
        /// Test the property 'InstitutionId'
        /// </summary>
        [Fact]
        public void InstitutionIdTest()
        {
            // TODO unit test for the property 'InstitutionId'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'FundId'
        /// </summary>
        [Fact]
        public void FundIdTest()
        {
            // TODO unit test for the property 'FundId'
        }

    }

}
