/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///     Class for testing FixedPaymentInterestTermsAllOf
    /// </summary>
    /// <remarks>
    ///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    ///     Please update the test case below to test the model.
    /// </remarks>
    public class FixedPaymentInterestTermsAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FixedPaymentInterestTermsAllOf
        //private FixedPaymentInterestTermsAllOf instance;

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        ///     Test an instance of FixedPaymentInterestTermsAllOf
        /// </summary>
        [Fact]
        public void FixedPaymentInterestTermsAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FixedPaymentInterestTermsAllOf
            //Assert.IsInstanceOfType<FixedPaymentInterestTermsAllOf> (instance, "variable 'instance' is a FixedPaymentInterestTermsAllOf");
        }


        /// <summary>
        ///     Test the property 'PaymentAmount'
        /// </summary>
        [Fact]
        public void PaymentAmountTest()
        {
            // TODO unit test for the property 'PaymentAmount'
        }
    }
}