/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing FloatingInterestTerms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FloatingInterestTermsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FloatingInterestTerms
        //private FloatingInterestTerms instance;

        public FloatingInterestTermsTests()
        {
            // TODO uncomment below to create an instance of FloatingInterestTerms
            //instance = new FloatingInterestTerms();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FloatingInterestTerms
        /// </summary>
        [Fact]
        public void FloatingInterestTermsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FloatingInterestTerms
            //Assert.IsInstanceOfType<FloatingInterestTerms> (instance, "variable 'instance' is a FloatingInterestTerms");
        }


        /// <summary>
        /// Test the property 'Benchmark'
        /// </summary>
        [Fact]
        public void BenchmarkTest()
        {
            // TODO unit test for the property 'Benchmark'
        }

    }

}
