/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing FloatingInterestRules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FloatingInterestRulesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FloatingInterestRules
        //private FloatingInterestRules instance;

        public FloatingInterestRulesTests()
        {
            // TODO uncomment below to create an instance of FloatingInterestRules
            //instance = new FloatingInterestRules();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FloatingInterestRules
        /// </summary>
        [Fact]
        public void FloatingInterestRulesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FloatingInterestRules
            //Assert.IsInstanceOfType<FloatingInterestRules> (instance, "variable 'instance' is a FloatingInterestRules");
        }


        /// <summary>
        /// Test the property 'Benchmarks'
        /// </summary>
        [Fact]
        public void BenchmarksTest()
        {
            // TODO unit test for the property 'Benchmarks'
        }

    }

}
