/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///     Class for testing Identity
    /// </summary>
    /// <remarks>
    ///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    ///     Please update the test case below to test the model.
    /// </remarks>
    public class IdentityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Identity
        //private Identity instance;

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        ///     Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }


        /// <summary>
        ///     Test the property 'Connection'
        /// </summary>
        [Fact]
        public void ConnectionTest()
        {
            // TODO unit test for the property 'Connection'
        }

        /// <summary>
        ///     Test an instance of Identity
        /// </summary>
        [Fact]
        public void IdentityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Identity
            //Assert.IsInstanceOfType<Identity> (instance, "variable 'instance' is a Identity");
        }

        /// <summary>
        ///     Test the property 'IsSocial'
        /// </summary>
        [Fact]
        public void IsSocialTest()
        {
            // TODO unit test for the property 'IsSocial'
        }

        /// <summary>
        ///     Test the property 'ProfileData'
        /// </summary>
        [Fact]
        public void ProfileDataTest()
        {
            // TODO unit test for the property 'ProfileData'
        }

        /// <summary>
        ///     Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        ///     Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
    }
}