/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing Institution
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstitutionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Institution
        //private Institution instance;

        public InstitutionTests()
        {
            // TODO uncomment below to create an instance of Institution
            //instance = new Institution();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Institution
        /// </summary>
        [Fact]
        public void InstitutionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Institution
            //Assert.IsInstanceOfType<Institution> (instance, "variable 'instance' is a Institution");
        }


        /// <summary>
        /// Test the property 'InstitutionId'
        /// </summary>
        [Fact]
        public void InstitutionIdTest()
        {
            // TODO unit test for the property 'InstitutionId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Fact]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

    }

}
