/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing InterestRules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InterestRulesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InterestRules
        //private InterestRules instance;

        public InterestRulesTests()
        {
            // TODO uncomment below to create an instance of InterestRules
            //instance = new InterestRules();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InterestRules
        /// </summary>
        [Fact]
        public void InterestRulesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InterestRules
            //Assert.IsInstanceOfType<InterestRules> (instance, "variable 'instance' is a InterestRules");
        }

        /// <summary>
        /// Test deserialize a FloatingInterestRules from type InterestRules
        /// </summary>
        [Fact]
        public void FloatingInterestRulesDeserializeFromInterestRulesTest()
        {
            // TODO uncomment below to test deserialize a FloatingInterestRules from type InterestRules
            //Assert.IsInstanceOf<InterestRules>(JsonConvert.DeserializeObject<InterestRules>(new FloatingInterestRules().ToJson()));
        }
        /// <summary>
        /// Test deserialize a FixedPaymentInterestRules from type InterestRules
        /// </summary>
        [Fact]
        public void FixedPaymentInterestRulesDeserializeFromInterestRulesTest()
        {
            // TODO uncomment below to test deserialize a FixedPaymentInterestRules from type InterestRules
            //Assert.IsInstanceOf<InterestRules>(JsonConvert.DeserializeObject<InterestRules>(new FixedPaymentInterestRules().ToJson()));
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
