/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing PasswordAuthRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PasswordAuthRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PasswordAuthRequest
        //private PasswordAuthRequest instance;

        public PasswordAuthRequestTests()
        {
            // TODO uncomment below to create an instance of PasswordAuthRequest
            //instance = new PasswordAuthRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PasswordAuthRequest
        /// </summary>
        [Fact]
        public void PasswordAuthRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PasswordAuthRequest
            //Assert.IsInstanceOfType<PasswordAuthRequest> (instance, "variable 'instance' is a PasswordAuthRequest");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

    }

}
