/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///     Class for testing ProfileData
    /// </summary>
    /// <remarks>
    ///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    ///     Please update the test case below to test the model.
    /// </remarks>
    public class ProfileDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProfileData
        //private ProfileData instance;

        public void Dispose()
        {
            // Cleanup when everything is done.
        }


        /// <summary>
        ///     Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        ///     Test the property 'EmailVerified'
        /// </summary>
        [Fact]
        public void EmailVerifiedTest()
        {
            // TODO unit test for the property 'EmailVerified'
        }

        /// <summary>
        ///     Test the property 'FamilyName'
        /// </summary>
        [Fact]
        public void FamilyNameTest()
        {
            // TODO unit test for the property 'FamilyName'
        }

        /// <summary>
        ///     Test the property 'GivenName'
        /// </summary>
        [Fact]
        public void GivenNameTest()
        {
            // TODO unit test for the property 'GivenName'
        }

        /// <summary>
        ///     Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        ///     Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        ///     Test the property 'PhoneVerified'
        /// </summary>
        [Fact]
        public void PhoneVerifiedTest()
        {
            // TODO unit test for the property 'PhoneVerified'
        }

        /// <summary>
        ///     Test an instance of ProfileData
        /// </summary>
        [Fact]
        public void ProfileDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProfileData
            //Assert.IsInstanceOfType<ProfileData> (instance, "variable 'instance' is a ProfileData");
        }

        /// <summary>
        ///     Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
    }
}