/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///     Class for testing RecordLoanSaleRequest
    /// </summary>
    /// <remarks>
    ///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    ///     Please update the test case below to test the model.
    /// </remarks>
    public class RecordLoanSaleRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecordLoanSaleRequest
        //private RecordLoanSaleRequest instance;

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        ///     Test an instance of RecordLoanSaleRequest
        /// </summary>
        [Fact]
        public void RecordLoanSaleRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecordLoanSaleRequest
            //Assert.IsInstanceOfType<RecordLoanSaleRequest> (instance, "variable 'instance' is a RecordLoanSaleRequest");
        }


        /// <summary>
        ///     Test the property 'SaleData'
        /// </summary>
        [Fact]
        public void SaleDataTest()
        {
            // TODO unit test for the property 'SaleData'
        }
    }
}