/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing RevolverDrawRules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RevolverDrawRulesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RevolverDrawRules
        //private RevolverDrawRules instance;

        public RevolverDrawRulesTests()
        {
            // TODO uncomment below to create an instance of RevolverDrawRules
            //instance = new RevolverDrawRules();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RevolverDrawRules
        /// </summary>
        [Fact]
        public void RevolverDrawRulesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RevolverDrawRules
            //Assert.IsInstanceOfType<RevolverDrawRules> (instance, "variable 'instance' is a RevolverDrawRules");
        }


        /// <summary>
        /// Test the property 'Commitment'
        /// </summary>
        [Fact]
        public void CommitmentTest()
        {
            // TODO unit test for the property 'Commitment'
        }

    }

}
