/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing SystemStatusResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SystemStatusResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SystemStatusResponse
        //private SystemStatusResponse instance;

        public SystemStatusResponseTests()
        {
            // TODO uncomment below to create an instance of SystemStatusResponse
            //instance = new SystemStatusResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SystemStatusResponse
        /// </summary>
        [Fact]
        public void SystemStatusResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SystemStatusResponse
            //Assert.IsInstanceOfType<SystemStatusResponse> (instance, "variable 'instance' is a SystemStatusResponse");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
