/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///     Class for testing Tranche
    /// </summary>
    /// <remarks>
    ///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    ///     Please update the test case below to test the model.
    /// </remarks>
    public class TrancheTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Tranche
        //private Tranche instance;

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        ///     Test the property 'CommitmentAmount'
        /// </summary>
        [Fact]
        public void CommitmentAmountTest()
        {
            // TODO unit test for the property 'CommitmentAmount'
        }


        /// <summary>
        ///     Test the property 'TrancheId'
        /// </summary>
        [Fact]
        public void TrancheIdTest()
        {
            // TODO unit test for the property 'TrancheId'
        }

        /// <summary>
        ///     Test an instance of Tranche
        /// </summary>
        [Fact]
        public void TrancheInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Tranche
            //Assert.IsInstanceOfType<Tranche> (instance, "variable 'instance' is a Tranche");
        }
    }
}