/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing Tranche
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrancheTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Tranche
        //private Tranche instance;

        public TrancheTests()
        {
            // TODO uncomment below to create an instance of Tranche
            //instance = new Tranche();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Tranche
        /// </summary>
        [Fact]
        public void TrancheInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Tranche
            //Assert.IsInstanceOfType<Tranche> (instance, "variable 'instance' is a Tranche");
        }


        /// <summary>
        /// Test the property 'TrancheId'
        /// </summary>
        [Fact]
        public void TrancheIdTest()
        {
            // TODO unit test for the property 'TrancheId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Draw'
        /// </summary>
        [Fact]
        public void DrawTest()
        {
            // TODO unit test for the property 'Draw'
        }
        /// <summary>
        /// Test the property 'Interest'
        /// </summary>
        [Fact]
        public void InterestTest()
        {
            // TODO unit test for the property 'Interest'
        }

    }

}
