/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LoanStreet.LoanServicing.Api;
using LoanStreet.LoanServicing.Model;
using LoanStreet.LoanServicing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LoanStreet.LoanServicing.Test
{
    /// <summary>
    ///  Class for testing User
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for User
        //private User instance;

        public UserTests()
        {
            // TODO uncomment below to create an instance of User
            //instance = new User();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of User
        /// </summary>
        [Fact]
        public void UserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" User
            //Assert.IsInstanceOfType<User> (instance, "variable 'instance' is a User");
        }


        /// <summary>
        /// Test the property 'Connection'
        /// </summary>
        [Fact]
        public void ConnectionTest()
        {
            // TODO unit test for the property 'Connection'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'VerifyPassword'
        /// </summary>
        [Fact]
        public void VerifyPasswordTest()
        {
            // TODO unit test for the property 'VerifyPassword'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'EmailVerified'
        /// </summary>
        [Fact]
        public void EmailVerifiedTest()
        {
            // TODO unit test for the property 'EmailVerified'
        }
        /// <summary>
        /// Test the property 'VerifyEmail'
        /// </summary>
        [Fact]
        public void VerifyEmailTest()
        {
            // TODO unit test for the property 'VerifyEmail'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'PhoneVerified'
        /// </summary>
        [Fact]
        public void PhoneVerifiedTest()
        {
            // TODO unit test for the property 'PhoneVerified'
        }
        /// <summary>
        /// Test the property 'VerifyPhoneNumber'
        /// </summary>
        [Fact]
        public void VerifyPhoneNumberTest()
        {
            // TODO unit test for the property 'VerifyPhoneNumber'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Fact]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Fact]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }
        /// <summary>
        /// Test the property 'GivenName'
        /// </summary>
        [Fact]
        public void GivenNameTest()
        {
            // TODO unit test for the property 'GivenName'
        }
        /// <summary>
        /// Test the property 'FamilyName'
        /// </summary>
        [Fact]
        public void FamilyNameTest()
        {
            // TODO unit test for the property 'FamilyName'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Identities'
        /// </summary>
        [Fact]
        public void IdentitiesTest()
        {
            // TODO unit test for the property 'Identities'
        }
        /// <summary>
        /// Test the property 'AppMetadata'
        /// </summary>
        [Fact]
        public void AppMetadataTest()
        {
            // TODO unit test for the property 'AppMetadata'
        }
        /// <summary>
        /// Test the property 'UserMetadata'
        /// </summary>
        [Fact]
        public void UserMetadataTest()
        {
            // TODO unit test for the property 'UserMetadata'
        }
        /// <summary>
        /// Test the property 'Multifactor'
        /// </summary>
        [Fact]
        public void MultifactorTest()
        {
            // TODO unit test for the property 'Multifactor'
        }
        /// <summary>
        /// Test the property 'LastIp'
        /// </summary>
        [Fact]
        public void LastIpTest()
        {
            // TODO unit test for the property 'LastIp'
        }
        /// <summary>
        /// Test the property 'LastLogin'
        /// </summary>
        [Fact]
        public void LastLoginTest()
        {
            // TODO unit test for the property 'LastLogin'
        }
        /// <summary>
        /// Test the property 'LoginsCount'
        /// </summary>
        [Fact]
        public void LoginsCountTest()
        {
            // TODO unit test for the property 'LoginsCount'
        }
        /// <summary>
        /// Test the property 'Blocked'
        /// </summary>
        [Fact]
        public void BlockedTest()
        {
            // TODO unit test for the property 'Blocked'
        }

    }

}
