/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = LoanStreet.LoanServicing.Client.OpenAPIDateConverter;

namespace LoanStreet.LoanServicing.Model
{
    /// <summary>
    /// FixedPaymentInterestTerms
    /// </summary>
    [DataContract]
    public partial class FixedPaymentInterestTerms : InterestTerms,  IEquatable<FixedPaymentInterestTerms>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FixedPaymentInterestTerms" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FixedPaymentInterestTerms() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FixedPaymentInterestTerms" /> class.
        /// </summary>
        /// <param name="paymentAmount">paymentAmount (required).</param>
        /// <param name="effectiveDate">effectiveDate (required).</param>
        /// <param name="annualRate">annualRate (required).</param>
        /// <param name="dayCount">dayCount (required).</param>
        /// <param name="compounding">compounding (required).</param>
        /// <param name="benchmark">benchmark.</param>
        /// <param name="interestType">interestType (required).</param>
        /// <param name="numAmortizationPeriods">numAmortizationPeriods (required).</param>
        /// <param name="numInterestOnlyPeriods">numInterestOnlyPeriods (required).</param>
        /// <param name="numPeriods">numPeriods (required).</param>
        /// <param name="paymentFrequency">paymentFrequency (required).</param>
        public FixedPaymentInterestTerms(Money paymentAmount = default(Money), DateTime effectiveDate = default(DateTime), double annualRate = default(double), DayCountEnum dayCount = default(DayCountEnum), CompoundingEnum compounding = default(CompoundingEnum), BenchmarkEnum? benchmark = default(BenchmarkEnum?), InterestTypeEnum interestType = default(InterestTypeEnum), int numAmortizationPeriods = default(int), int numInterestOnlyPeriods = default(int), int numPeriods = default(int), PaymentFrequencyEnum paymentFrequency = default(PaymentFrequencyEnum)) : base(effectiveDate, annualRate, dayCount, compounding, benchmark, interestType, numAmortizationPeriods, numInterestOnlyPeriods, numPeriods, paymentFrequency)
        {
            // to ensure "paymentAmount" is required (not null)
            if (paymentAmount == null)
            {
                throw new InvalidDataException("paymentAmount is a required property for FixedPaymentInterestTerms and cannot be null");
            }
            else
            {
                this.PaymentAmount = paymentAmount;
            }

        }
        
        /// <summary>
        /// Gets or Sets PaymentAmount
        /// </summary>
        [DataMember(Name="paymentAmount", EmitDefaultValue=false)]
        public Money PaymentAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FixedPaymentInterestTerms {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  PaymentAmount: ").Append(PaymentAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FixedPaymentInterestTerms);
        }

        /// <summary>
        /// Returns true if FixedPaymentInterestTerms instances are equal
        /// </summary>
        /// <param name="input">Instance of FixedPaymentInterestTerms to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FixedPaymentInterestTerms input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.PaymentAmount == input.PaymentAmount ||
                    (this.PaymentAmount != null &&
                    this.PaymentAmount.Equals(input.PaymentAmount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.PaymentAmount != null)
                    hashCode = hashCode * 59 + this.PaymentAmount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
