/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = LoanStreet.LoanServicing.Client.OpenAPIDateConverter;

namespace LoanStreet.LoanServicing.Model
{
    /// <summary>
    /// Loan
    /// </summary>
    [DataContract]
    public partial class Loan :  IEquatable<Loan>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Loan" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Loan() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Loan" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="timeZoneId">timeZoneId.</param>
        /// <param name="institutions">institutions (required).</param>
        /// <param name="draw">draw.</param>
        /// <param name="interest">interest.</param>
        public Loan(string name = default(string), string timeZoneId = default(string), List<FacilityInstitutionDto> institutions = default(List<FacilityInstitutionDto>), DrawRules draw = default(DrawRules), InterestRules interest = default(InterestRules))
        {
            // to ensure "institutions" is required (not null)
            this.Institutions = institutions ?? throw new ArgumentNullException("institutions is a required property for Loan and cannot be null");;
            this.Name = name;
            this.TimeZoneId = timeZoneId;
            this.Draw = draw;
            this.Interest = interest;
        }
        
        /// <summary>
        /// Gets or Sets LoanId
        /// </summary>
        [DataMember(Name="loanId", EmitDefaultValue=false)]
        public string LoanId { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets TimeZoneId
        /// </summary>
        [DataMember(Name="timeZoneId", EmitDefaultValue=false)]
        public string TimeZoneId { get; set; }

        /// <summary>
        /// Gets or Sets Institutions
        /// </summary>
        [DataMember(Name="institutions", EmitDefaultValue=false)]
        public List<FacilityInstitutionDto> Institutions { get; set; }

        /// <summary>
        /// Gets or Sets Draw
        /// </summary>
        [DataMember(Name="draw", EmitDefaultValue=false)]
        public DrawRules Draw { get; set; }

        /// <summary>
        /// Gets or Sets Interest
        /// </summary>
        [DataMember(Name="interest", EmitDefaultValue=false)]
        public InterestRules Interest { get; set; }

        /// <summary>
        /// Gets or Sets Borrowings
        /// </summary>
        [DataMember(Name="borrowings", EmitDefaultValue=false)]
        public List<Borrowing> Borrowings { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Loan {\n");
            sb.Append("  LoanId: ").Append(LoanId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  TimeZoneId: ").Append(TimeZoneId).Append("\n");
            sb.Append("  Institutions: ").Append(Institutions).Append("\n");
            sb.Append("  Draw: ").Append(Draw).Append("\n");
            sb.Append("  Interest: ").Append(Interest).Append("\n");
            sb.Append("  Borrowings: ").Append(Borrowings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Loan);
        }

        /// <summary>
        /// Returns true if Loan instances are equal
        /// </summary>
        /// <param name="input">Instance of Loan to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Loan input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LoanId == input.LoanId ||
                    (this.LoanId != null &&
                    this.LoanId.Equals(input.LoanId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.TimeZoneId == input.TimeZoneId ||
                    (this.TimeZoneId != null &&
                    this.TimeZoneId.Equals(input.TimeZoneId))
                ) && 
                (
                    this.Institutions == input.Institutions ||
                    this.Institutions != null &&
                    input.Institutions != null &&
                    this.Institutions.SequenceEqual(input.Institutions)
                ) && 
                (
                    this.Draw == input.Draw ||
                    (this.Draw != null &&
                    this.Draw.Equals(input.Draw))
                ) && 
                (
                    this.Interest == input.Interest ||
                    (this.Interest != null &&
                    this.Interest.Equals(input.Interest))
                ) && 
                (
                    this.Borrowings == input.Borrowings ||
                    this.Borrowings != null &&
                    input.Borrowings != null &&
                    this.Borrowings.SequenceEqual(input.Borrowings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LoanId != null)
                    hashCode = hashCode * 59 + this.LoanId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.TimeZoneId != null)
                    hashCode = hashCode * 59 + this.TimeZoneId.GetHashCode();
                if (this.Institutions != null)
                    hashCode = hashCode * 59 + this.Institutions.GetHashCode();
                if (this.Draw != null)
                    hashCode = hashCode * 59 + this.Draw.GetHashCode();
                if (this.Interest != null)
                    hashCode = hashCode * 59 + this.Interest.GetHashCode();
                if (this.Borrowings != null)
                    hashCode = hashCode * 59 + this.Borrowings.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
