/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = LoanStreet.LoanServicing.Client.OpenAPIDateConverter;

namespace LoanStreet.LoanServicing.Model
{
    /// <summary>
    /// RecordLoanSaleRequest
    /// </summary>
    [DataContract]
    public partial class RecordLoanSaleRequest :  IEquatable<RecordLoanSaleRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordLoanSaleRequest" /> class.
        /// </summary>
        /// <param name="saleData">saleData.</param>
        public RecordLoanSaleRequest(LoanSaleData saleData = default(LoanSaleData))
        {
            this.SaleData = saleData;
        }
        
        /// <summary>
        /// Gets or Sets SaleData
        /// </summary>
        [DataMember(Name="saleData", EmitDefaultValue=false)]
        public LoanSaleData SaleData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RecordLoanSaleRequest {\n");
            sb.Append("  SaleData: ").Append(SaleData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RecordLoanSaleRequest);
        }

        /// <summary>
        /// Returns true if RecordLoanSaleRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of RecordLoanSaleRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RecordLoanSaleRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SaleData == input.SaleData ||
                    (this.SaleData != null &&
                    this.SaleData.Equals(input.SaleData))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SaleData != null)
                    hashCode = hashCode * 59 + this.SaleData.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
