/* 
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = LoanStreet.LoanServicing.Client.OpenAPIDateConverter;

namespace LoanStreet.LoanServicing.Model
{
    /// <summary>
    /// RevolverDrawRules
    /// </summary>
    [DataContract]
    public partial class RevolverDrawRules : DrawRules,  IEquatable<RevolverDrawRules>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RevolverDrawRules" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RevolverDrawRules() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RevolverDrawRules" /> class.
        /// </summary>
        /// <param name="commitment">commitment (required).</param>
        /// <param name="date">date (required).</param>
        /// <param name="type">type (required).</param>
        public RevolverDrawRules(Money commitment = default(Money), DateTime date = default(DateTime), string type = default(string)) : base(date, type)
        {
            // to ensure "commitment" is required (not null)
            this.Commitment = commitment ?? throw new ArgumentNullException("commitment is a required property for RevolverDrawRules and cannot be null");;
        }
        
        /// <summary>
        /// Gets or Sets Commitment
        /// </summary>
        [DataMember(Name="commitment", EmitDefaultValue=false)]
        public Money Commitment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RevolverDrawRules {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Commitment: ").Append(Commitment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RevolverDrawRules);
        }

        /// <summary>
        /// Returns true if RevolverDrawRules instances are equal
        /// </summary>
        /// <param name="input">Instance of RevolverDrawRules to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RevolverDrawRules input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Commitment == input.Commitment ||
                    (this.Commitment != null &&
                    this.Commitment.Equals(input.Commitment))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Commitment != null)
                    hashCode = hashCode * 59 + this.Commitment.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
