name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Dev Build
      run: dotnet build --configuration Debug
    - name: Fluent Builder
      run: flubu run.tests
    - name: Test
      run: make test_generated
    - name: Build with dotnet
      run: dotnet build --configuration Release
